### ISSUE TITLE
Invalid gemspec in [...] invalid date format in specification: "2011-06-06 00:00:00.000000000Z"

### ISSUE THREAD

**Issue by byu** [mikbe/eventable#1]
$ ruby --version
ruby 1.9.2p180 (2011-02-18 revision 30909) [i386-darwin9.8.0]

$ gem --version
1.8.2

$ gem install eventable
Fetching: eventable-0.1.0.gem (100%)
Invalid gemspec in [~/.rvm/gems/ruby-1.9.2-p180@develop/specifications/eventable-0.1.0.gemspec]: invalid date format in specification: "2011-06-06 00:00:00.000000000Z"
ERROR:  While executing gem ... (NoMethodError)
    undefined method `name' for nil:NilClass
[~]
$ 

Now this error'd gemspec essentially denies the ruby system from being able to boot.

Removing the time segment from the gemspec seems to fix the problem.

**Comment by mikbe** [comment]
This is a "bug" in RubyGems. It has to do with how the dates are parsed if systems use different date parsers (syck vs. psych) though I've had the issue even when they do. They fixed RubyGems but I didn't specify the fix in my gemspec [edit] so it will work with older versions of RubyGems[/edit], will do that now. Thanks again!

**Comment by mikbe** [comment]
Fixed. Released 0.1.1 with fixes for issue #1 and # 2
