### ISSUE TITLE
calling fire_event in an event class w/o first registering listeners raises and error.

### ISSUE THREAD

**Issue by byu** [mikbe/eventable#2]
```
$ irb
ruby-1.9.2-p180 :001 > require 'eventable'
 => true 
ruby-1.9.2-p180 :002 > 
ruby-1.9.2-p180 :003 >   class EventClass
ruby-1.9.2-p180 :004?>     include Eventable
ruby-1.9.2-p180 :005?>   
ruby-1.9.2-p180 :006 >       # This is all you have to do to add an event (after you include Eventable)
ruby-1.9.2-p180 :007 >       event :stuff_happens
ruby-1.9.2-p180 :008?>   
ruby-1.9.2-p180 :009 >       # don't name your method fire_event, that's taken
ruby-1.9.2-p180 :010 >       def do_event
ruby-1.9.2-p180 :011?>         puts "firing :stuff_happens"
ruby-1.9.2-p180 :012?>         # And this is all you have to do to make the event happen
ruby-1.9.2-p180 :013 >           fire_event(:stuff_happens, rand(1000))
ruby-1.9.2-p180 :014?>       end
ruby-1.9.2-p180 :015?>   
ruby-1.9.2-p180 :016 >     end
 => nil 
ruby-1.9.2-p180 :017 > 
ruby-1.9.2-p180 :018 >   # Create an instance of a class that has an event
ruby-1.9.2-p180 :019 >   evented   = EventClass.new
 => #<EventClass:0x1bad00> 
ruby-1.9.2-p180 :020 > # We'll just arbitrarilly fire the event to see how it works
ruby-1.9.2-p180 :021 >   evented.do_event
firing :stuff_happens
NoMethodError: undefined method `synchronize' for nil:NilClass
    from ~/.rvm/gems/ruby-1.9.2-p180@develop/gems/eventable-0.1.0/lib/eventable/eventable.rb:36:in `fire_event'
    from (irb):13:in `do_event'
    from (irb):21
    from ~/.rvm/rubies/ruby-1.9.2-p180/bin/irb:16:in `<main>'
ruby-1.9.2-p180 :022 > 
```

This is because [line 36 of eventable.rb](https://github.com/mikbe/eventable/blob/master/lib/eventable/eventable.rb#L36) tries to synchronize on a mutex that doesn't exist. The mutex is created in the registration of a first event.

Possible fix is to guard the synchronize call with a nil check?

The next thing, I'm not sure about because I'm unfamiliar with underlying language implementation in the VMs. This is me mostly just pondering because of the likelihood of this happening seems very small.

Also, could there exist a possible problem (seems very unlikely, but theoretically possible) when multiple threads attempt to register listeners at the same time on an event class that has had no previous registered listeners. The call:

```
    @mutex ||= Mutex.new
```

I don't think the ||= operator is atomic???  Thus it possibly be that thread A sees that @mutex is nil so it will create a new mutex. But before the assignment, that thread is immediately interrupted by thread B who is also registering an event. It goes past this line, creating a new mutex. Then thread A runs again, thus completing the mutex assignment. They both run code in the synchronized block... And proceeds to do unpredictable things in the ||= type assignments in the protected code w.r.t the @callbacks.

**Comment by mikbe** [comment]
Great catch, thanks. I'll write a spec for that and fix it.

**Comment by mikbe** [comment]
Fixed

**Comment by mikbe** [comment]
I didn't really address the concurrency issue with creating mutex lock because I felt throwing an error on no listeners was a pretty bad bug and wanted to fix it. 

I did think of a way to address your concern though. I can add a mutex at the class level that gets created as the class loads. Then I use that class level mutex to synchronize the creation of the instance level mutexes (mutexi?). That means instances will block each other as the first time they create a mutex but that shouldn't happen very often and it would be really quick any way.

I can't but think this solution sounds really hokey though... I'm going to see if there is a cleaner way to do it.

**Comment by byu** [comment]
I concur.

**Comment by byu** [comment]
What about overriding the `new` class method? Then the mutex is set on construction of the object so we don't need a second "class" mutex.

```
def self.included(base)
  base.extend(EventableClassMethods)
  class << base 
   alias_method :_new, :new
    def new(*args)
      o = _new(*args)
      o.instance_variable_set :@eventable_mutex, Mutex.new
      return o
    end
  end
end
```
